import "./modules/loader";
import "./modules/swiper";
import "./modules/client-line";
import "./modules/img-zoom";
import "./modules/custom-select";
import "./modules/input-number-mask";
import "./modules/order-form";
import "./modules/accordeons-init";
import "./modules/tab-init";
